# Generated by Django 3.2.15 on 2022-09-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='des',
            new_name='priority',
        ),
    ]
