# Generated by Django 3.2.15 on 2022-09-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_des_todo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(default='1999-09-21'),
            preserve_default=False,
        ),
    ]
